title: "Ross Spencer: MADCT Portfolio, Kings College London, 2005"
description: Portfolio for MADCT (Material Culture and Technology) @ Kings College London (2005)
theme: just-the-docs
color_scheme: dark
search_enabled: true

url: https://ross-spencer.github.io/madct/

aux_links:
  github: https://github.com/ross-spencer/madct
  blog: https://exponentialdecay.co.uk/blog
  hand drawn: https://exponentialdecay.co.uk/prototype-comicbook/